services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: pdf_tucano
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgresPASS123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresuser -d pdf_tucano"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  pdf-tucano:
    build: .
    restart: unless-stopped    
    environment:
      DATABASE_URL: postgresql+psycopg2://postgresuser:postgresPASS123@postgres:5432/pdf_tucano
      OPENROUTER_MODEL: google/gemini-2.0-flash-001
      PAGE_IMAGE_WIDTH: 1500
      PAGE_IMAGE_DPI: 300
      MAX_CONCURRENT_PAGES: 8
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      LOG_LEVEL: DEBUG
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - pdfdata:/data

volumes:
  pgdata:
  pdfdata:
